name: Notify Discord on Commit

on:
  push:
    branches:
      - datapack

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Format and send commit message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"📦 **New commit** by \`${GITHUB_ACTOR}\`:\n> ${COMMIT_MSG}\n🔗 ${COMMIT_URL}\"}" \
          $DISCORD_WEBHOOK
